version: "3.9"
services:
  app:
    build: .
    container_name: spring-app
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      AWS_CREDENTIALS_ACCESS_KEY: ${AWS_S3_ACCESS_KEY}
      AWS_CREDENTIALS_SECRET_KEY: ${AWS_S3_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      TZ: Asia/Seoul
      JVM_OPTS: "-Duser.timezone=Asia/Seoul"
    ports:
      - "8081:8081"
    networks:
      - backend

networks:
  backend:
