version: '3.8'

services:
  app:
    image: discodeit:local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discodeit
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/discodeit
      - SPRING_DATASOURCE_USERNAME=${POSTGRESQL_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRESQL_DATASOURCE_PASSWORD}
      - STORAGE_TYPE=local
      - DISCODEIT_ADMIN_USERNAME=${DISCODEIT_ADMIN_USERNAME}
      - DISCODEIT_ADMIN_EMAIL=${DISCODEIT_ADMIN_EMAIL}
      - DISCODEIT_ADMIN_PASSWORD=${DISCODEIT_ADMIN_PASSWORD}
    depends_on:
      - db
    volumes:
      - binary-content-storage:/app/.discodeit/storage
    networks:
      - discodeit-network

  db:
    image: postgres:16-alpine
    container_name: discodeit-db
    environment:
      - POSTGRES_DB=discodeit
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - discodeit-network

  broker:
      image: apache/kafka:latest
      hostname: broker
      container_name: broker
      ports:
        - 29092:29092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_NODE_ID: 1
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
        CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      networks:
        - discodeit-network


volumes:
  postgres-data:
  binary-content-storage:

networks:
  discodeit-network:
    driver: bridge 